title: Camille Le Coz
description: &description "personal homepage"
url: https://clecoz.github.io


# Site Author
author:
  name: Camille Le Coz
  email: clecoz.le-coz@lmd.ipsl.fr
  github: clecoz
  
  
# Build settings
markdown: kramdown
theme: minima
#remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-remote-theme 
