title: Camille Le Coz
description: &description "personal homepage"
url: https://clecoz.github.io
email: camille.le-coz@lmd.ipsl.fr
github_username:  clecoz

social-network-links:
  googlescholar: https://scholar.google.fr/citations?user=pvBg6YcAAAAJ&hl=en&oi=ao
  github: clecoz
  
# Build settings
markdown: kramdown
theme: minima
#remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-remote-theme 
