title: Camille Le Coz
subtitle: postdoctoral researcher
description: &description "personal homepage"
url: https://clecoz.github.io
email: camille.le-coz@lmd.ipsl.fr
#github_username:  clecoz



# Build settings
markdown: kramdown
theme: minima
#remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-remote-theme 


# Analytics
analytics:
  provider               :  "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
