title: Camille Le Coz
email: camille.le-coz@lmd.ipsl.fr
github_username:  clecoz

# Build settings
markdown: kramdown
#theme: minima
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
# - jekyll-remote-theme 
